matrix:
  include:
    - language: python
      python:
        - "3.6"
      install:
        - pip install boto3 codecov coverage
      # commands to run tests
      script:
        - cd ./gtfs/gtfs_utils
        - python setup.py test
        - cd ../retriever/
        - coverage run s3_wrapper_setup.py pytest
        - codecov
    - language: java
      jdk: oraclejdk8
      script:
        - cd ./siri/siri_retriever/siri-0.1
        - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        - docker build -t hasadna/siri-collector:latest .
