language: python
python: 
  - "3.6"
install:
  - pip install boto3 codecov coverage
# commands to run tests
script: 
  - cd ./gtfs/gtfs_utils
  - python setup.py test
  - cd ../retriever/
  - coverage run s3_wrapper_setup.py pytest
  - codecov
